# DATA PROCESSING

## Datasets Overview
This notebook demonstrates how we pre-process weather data before training models. There are 2 datasets that we selected for this project. Here are overview of these 2 datasets:

### Dataset 1: Australia Weather Data (Kaggle)
*   Source: Visualcrossing.com, a platform known for providing accurate historical weather data.
*   Scope: This dataset comprises weather observations collected from various weather stations across Australia, including Melbourne, spanning from 2008 to 2017.


### Dataset 2: Melbourne Weather Data (Visualcrossing)
*   Source: Visualcrossing.com, a platform known for providing accurate historical weather data.
*   Scope: This dataset focuses specifically on Melbourne weather data, providing detailed daily observations for a more localized analysis.

## Necessary Libraries
First of all, we import all necessary Python libraries for data processing. Here is list of libraries used for this notebook:


*   NumPy: For handling of numerical data and performing mathematical operations on arrays which is essential for data manipulation and analysis.

*   Pandas: Used for loading, cleaning, and manipulating structured data in DataFrames.

*   OS: To interact with the file system, such as navigating directories or loading datasets from specific file paths.

*   Seaborn: Used for creating visual statistical plots, helping to explore data patterns and distributions.

*   Matplotlib: For generating visualizations, used with Seaborn to enhance data visualization.

*   Scikit-learn (preprocessing module): Provides tools to standardize, handle missing values before feeding the data into machine learning models.

In [ ]:
import numpy as np
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing
import warnings

warnings.filterwarnings("ignore")

## 1. Dataset 1 - Australia Weather Dataset (Kaggle)

### 1.1. Dataset 1 - Loading and Descriptions



*   We read Australia Weather Dataset into Pandas dataframe.

*   Next, we sets the column 'Date' as the index for the dataframe.
The inplace argument ensures that the change is made directly to dataset1.

*   Then we displayed the first 5 rows in our dataset.

In [ ]:
dataset1 = pd.read_csv('weatherAUS.csv')
dataset1.set_index('Date', inplace=True)
dataset1.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,WNW,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,WSW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,WSW,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,E,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,NW,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

After running the following lines of code above, you will see all the weather variables of the first dataset. In case of some variables' naming abbrieviation are unclear, we provides descriptions for all 23 weather metrics:

*   Date: Date of the weather observation
*   Location: Name of the city from Australia
*   MinTemp: Minimum temperature recorded during the day (°C)
*   MaxTemp: Maximum temperature recorded during the day (°C)
*   Rainfall: Amount of rain recorded during a day (mm)
*   Evaporation: Amount of water lost to evaporation during a day (mm)
*   Sunshine: Duration of bright sunshine during the day (hours)
*   WindGustDir: Direction from which the strongest wind gust was coming (16 compass points)
*   WindGustSpeed: Speed of the strongest wind gust recorded (km/h)
*   WindDir9am: Wind direction at 9 a.m(compass points)
*   WindDir3pm: Wind direction at 3 p.m (compass points)
*   WindSpeed9am: Speed of the wind at 9 a.m (km/h)
*   WindSpeed3pm: Speed of the wind at 3 p.m (km/h)
*   Humidity9am: 	Humidity percentage at 9 a.m (%)
*   Humidity3pm: 	Humidity percentage at 3 p.m (%)
*   Pressure9am: Atmospheric pressure at 9 a.m (hPa)
*   Pressure3pm: Atmospheric pressure at 3 p.m (hPa)
*   Cloud9am: Cloud cover at 9 a.m (eighths)
*   Cloud3pm: Cloud cover at 3 p.m (eighths)
*   Temp9am: Temperature at 9 a.m (°C)
*   Temp3pm: Temperature at 3 p.m (°C)
*   RainToday: Whether rain was recorded today. If today is rainy then ‘Yes’. If today is not rainy then ‘No’.
*   RainTomorrow: Whether rain is forecast for the next day. If tomorrow is rainy then 1 (Yes). If tomorrow is not rainy then 0 (No).

### 1.2. Dataset 1 - Dealing with unstandardized values
For unstandardized values in 'RainToday' and 'RainTomorrow', we used mapping function map(). To be more detailed:


*   'Yes' is replaced by 1
*   'No' is replaced by 0

In [ ]:
dataset1['RainTomorrow'] = dataset1['RainTomorrow'].map({'Yes': 1, 'No': 0})
dataset1['RainToday'] = dataset1['RainToday'].map({'Yes': 1, 'No': 0})




*   Similar to the previous variables, variables such as 'WindDir9am', 'WindDir3pm', and 'WindGustDir' have categorical values like 'N', 'S', 'SW', etc.
*   Although these values are human-readable known as directions: West, East, South, etc, machine-learning algorithm can not handle these categorical values.

*   Our solution is using LabelEncoder to convert these categorical string values in listed columns into numerical values.

In [ ]:
le = preprocessing.LabelEncoder()
dataset1['WindDir9am'] = le.fit_transform(dataset1['WindDir9am'])
dataset1['WindDir3pm'] = le.fit_transform(dataset1['WindDir3pm'])
dataset1['WindGustDir'] = le.fit_transform(dataset1['WindGustDir'])

### 1.3. Dataset 1 - Pre-processing Result



*   Now, you can execute the below line of code for the first 5 rows of verification of the above data-precessing steps.
*   Notice that the values in the 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday' and 'RainTomorrow' columns is replaced by numerical values

In [ ]:
dataset1.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,13,44.0,13,14,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,0.0,0.0
2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,14,44.0,6,15,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,0.0,0.0
2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,15,46.0,13,15,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,0.0,0.0
2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,4,24.0,9,0,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,0.0,0.0
2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,13,41.0,1,7,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,0.0,0.0

### 1.4. Dataset 1 - Subset data for Melbourne location

We subset the data for Melbourne location only that focuses on our scope which is Melbourne Weather Prediction.

In [ ]:
melbourne_data1 = dataset1[dataset1['Location'] == 'Melbourne']
melbourne_data1.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2008-07-01,Melbourne,9.5,15.4,2.0,2.8,7.0,13,63.0,13,13,...,60.0,38.0,1006.8,1010.3,1.0,7.0,11.0,14.6,1.0,0.0
2008-07-02,Melbourne,11.0,14.5,0.6,5.2,4.0,13,63.0,13,15,...,66.0,52.0,1013.4,1016.2,7.0,4.0,11.8,13.7,0.0,1.0
2008-07-03,Melbourne,8.4,14.1,1.4,2.0,0.8,13,39.0,13,13,...,72.0,58.0,1024.8,1024.3,7.0,7.0,10.6,13.9,1.0,0.0
2008-07-04,Melbourne,9.1,14.5,0.6,1.8,4.2,0,19.0,6,3,...,87.0,49.0,1030.2,1029.0,7.0,6.0,10.2,13.1,0.0,0.0
2008-07-05,Melbourne,4.3,15.5,0.0,0.8,8.4,3,52.0,3,5,...,81.0,52.0,1028.9,1024.9,2.0,5.0,5.5,14.6,0.0,0.0

### 1.5. Subset dataset - Pre-processing

After subsetting data for Melbourne location from dataset 1, we check the percentage of missing data in every column.

In [ ]:
#Checking percentage of missing data in every column
(melbourne_data1.isnull().sum()/len(melbourne_data1))*100

Location          0.000000
MinTemp          15.032884
MaxTemp          15.064203
Rainfall         23.739430
Evaporation       0.093956
Sunshine          0.031319
WindGustDir       0.000000
WindGustSpeed     0.438459
WindDir9am        0.000000
WindDir3pm        0.000000
WindSpeed9am      0.062637
WindSpeed3pm      0.000000
Humidity9am      15.095521
Humidity3pm      15.252114
Pressure9am      15.032884
Pressure3pm      15.126840
Cloud9am         32.383339
Cloud3pm         34.638271
Temp9am          15.064203
Temp3pm          15.158158
RainToday        23.739430
RainTomorrow     23.739430
dtype: float64

Consider outputs above, some columns have high percentage of missing value such as: 'MinTemp', 'MaxTemp', 'Cloud9am', 'Cloud3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Temp9am', 'Temp3pm'


Because we will merge this subset dataset to dataset 2 (visualcrossing.com), we drop these unnecessary and high missing value percentage columns which can replaced by similar columns in dataset 2:



*   MinTemp --> Tempmin

*   MaxTemp --> Tempmax

*   Cloud9am --> Cloudcover

*   Cloud3pm --> Cloudcover

*   Humidity9am --> Humidity

*   Humidity3pm --> Humidity

*   Pressure9am --> Sealevelpressure

*   Pressure3pm --> Sealevelpressure

*   Temp9am --> Temp

*   Temp3pm --> Temp

(Refer to data set 2 descriptions at section 2.1 below for more details of these metrics)

In [ ]:
melbourne_data1 = melbourne_data1.drop(columns=['MinTemp', 'MaxTemp', 'Cloud9am', 'Cloud3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Temp9am', 'Temp3pm'])
melbourne_data1.head()

,Location,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,
2008-07-01,Melbourne,2.0,2.8,7.0,13,63.0,13,13,37.0,35.0,1.0,0.0
2008-07-02,Melbourne,0.6,5.2,4.0,13,63.0,13,15,30.0,35.0,0.0,1.0
2008-07-03,Melbourne,1.4,2.0,0.8,13,39.0,13,13,17.0,24.0,1.0,0.0
2008-07-04,Melbourne,0.6,1.8,4.2,0,19.0,6,3,9.0,7.0,0.0,0.0
2008-07-05,Melbourne,0.0,0.8,8.4,3,52.0,3,5,24.0,30.0,0.0,0.0

## 2. Dataset 2 - Melbourne Weather Dataset (visualcrossing.com)

### 2.1. Dataset 2 - Loading and Descriptions





*   We read Melbourne Weather Dataset into Pandas dataframe.

*   We covert 'datatime' column to 'data' to be compatible with the first dataset.

*   Then we displayed the first 5 rows in our dataset.

In [ ]:
melbourne_data2 = pd.read_csv('visualcrossing.csv')
melbourne_data2.rename(columns={'datetime': 'Date'}, inplace=True)
melbourne_data2.set_index('Date', inplace=True)
melbourne_data2.head()

,name,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
Date,,,,,,,,,,,,,,,,,,,,,
2008-07-01,"Melbourne,Australia",13.6,9.1,11.1,13.6,4.5,10.7,4.0,62.3,3.710,...,NaN,NaN,NaN,2008-07-01T07:36:29,2008-07-01T17:11:35,0.93,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,"95874099999,94866099999,95866099999,9486509999..."
2008-07-02,"Melbourne,Australia",12.9,6.1,10.6,12.9,3.1,9.8,5.5,71.5,2.861,...,NaN,NaN,NaN,2008-07-02T07:36:24,2008-07-02T17:12:03,0.96,"Rain, Partially cloudy",Partly cloudy throughout the day with rain in ...,rain,"95874099999,94866099999,95866099999,9486509999..."
2008-07-03,"Melbourne,Australia",12.5,6.6,9.6,12.5,3.2,8.3,5.9,78.4,0.274,...,NaN,NaN,NaN,2008-07-03T07:36:18,2008-07-03T17:12:33,0.00,"Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,rain,"95874099999,94866099999,95866099999,9486509999..."
2008-07-04,"Melbourne,Australia",13.1,3.7,8.9,13.1,3.7,8.5,5.9,83.4,0.295,...,NaN,NaN,NaN,2008-07-04T07:36:09,2008-07-04T17:13:04,0.03,"Rain, Partially cloudy",Partly cloudy throughout the day with rain cle...,rain,"95874099999,94866099999,95866099999,9486509999..."
2008-07-05,"Melbourne,Australia",15.1,1.2,7.9,15.1,-1.0,6.6,4.0,78.1,0.076,...,NaN,NaN,NaN,2008-07-05T07:35:59,2008-07-05T17:13:35,0.07,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,"95874099999,94866099999,95866099999,9486509999..."

After running the following lines of code above, you will see all the weather variables of the second dataset. In case of some variables' naming abbrieviation are unclear, we provides descriptions for all  weather metrics:

*   Date: Date of the weather observation
*   name: Location (Melbourne, Australia)
*   tempmax: Maximum temperature recorded during the day (°C)
*   tempmin: Minimum temperature recorded during the day (°C)
*   temp: Temperature (°C)
*   feelslikemax: Feels-like maximum temperature (°C)
*   feelslikemin: Feels-like minimum temperature (°C)
*   feelslike: Feels-like temperature (°C)
*   Dew: Dew point, indicates humidity level (°C)
*   Humidity: Humidity percentage (%)
*   Precip: Total rainfall (mm)
*   Precipprob: Chance of precipitation (%)
*   Precipcover: Area covered by precipitation (%)
*   Preciptype: Type of precipitation (e.g. rain)
*   Snow: Snowfall amount (mm/cm)
*   Snowdepth: Accumulated snow depth (cm)
*   Windgust: Speed of strongest wind gust (km/h)
*   Windspeed: Average wind speed (km/h)
*   Winddir: Wind direction (degrees)
*   Sealevelpressure: Atmospheric pressure at sea level (hPa)
*   Cloudcover: Cloud coverage (%)
*   Visibility: Visibility distance (m/km)
*   Solarradiation: Solar energy received (Wh/m²)
*   Solarenergy: Total solar energy (kWh/m²)
*   UVindex: Ultraviolet radiation level
*   Severerisk: Likelihood of severe weather
*   Sunrise: Time of sunrise
*   Sunset: Time of sunset
*   Moonphase: Current phase of the moon
*   Conditions: General weather condition (e.g., cloudy)
*   Description: Detailed weather summary
*   Icon: Weather icon representation
*   Stations: Source weather station IDs

### 2.2. Dataset 2 - Standardize Data and Drop Unnecessary Columns




*   The original format of 'Sunrise' and 'Sunset' columns is: 2008-07-01T07:36:29.

*   However, this is not a suitable value for AI model. We use convert_time_to_minutes fucntion() to take a time string in the format YYYY-MM-DDTHH:MM:SS.
*   Next, we uses 'strptime' from the 'datetime' module to parse the string.

*   After that, we converts the hours and minutes to total minutes since midnight (by multiplying the hours by 60 and adding the minutes).

*   Lastly, we use apply() method for each element in 'Sunrise' and 'Sunset' columns.

In [ ]:
# prompt: convert the sunrise and sunset time to suitable value for AI model, origin format: 2008-07-01T07:36:29

from datetime import datetime

def convert_time_to_minutes(time_str):
  """Converts a time string in the format 'YYYY-MM-DDTHH:MM:SS' to minutes since midnight."""
  try:
    dt = datetime.strptime(time_str, '%Y-%m-%dT%H:%M:%S')
    return (dt.hour * 60) + dt.minute
  except ValueError:
    return None

melbourne_data2['sunrise'] = melbourne_data2['sunrise'].apply(convert_time_to_minutes)
melbourne_data2['sunset'] = melbourne_data2['sunset'].apply(convert_time_to_minutes)
melbourne_data2

,name,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
Date,,,,,,,,,,,,,,,,,,,,,
2008-07-01,"Melbourne,Australia",13.6,9.1,11.1,13.6,4.5,10.7,4.0,62.3,3.710,...,NaN,NaN,NaN,456,1031,0.93,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,"95874099999,94866099999,95866099999,9486509999..."
2008-07-02,"Melbourne,Australia",12.9,6.1,10.6,12.9,3.1,9.8,5.5,71.5,2.861,...,NaN,NaN,NaN,456,1032,0.96,"Rain, Partially cloudy",Partly cloudy throughout the day with rain in ...,rain,"95874099999,94866099999,95866099999,9486509999..."
2008-07-03,"Melbourne,Australia",12.5,6.6,9.6,12.5,3.2,8.3,5.9,78.4,0.274,...,NaN,NaN,NaN,456,1032,0.00,"Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,rain,"95874099999,94866099999,95866099999,9486509999..."
2008-07-04,"Melbourne,Australia",13.1,3.7,8.9,13.1,3.7,8.5,5.9,83.4,0.295,...,NaN,NaN,NaN,456,1033,0.03,"Rain, Partially cloudy",Partly cloudy throughout the day with rain cle...,rain,"95874099999,94866099999,95866099999,9486509999..."
2008-07-05,"Melbourne,Australia",15.1,1.2,7.9,15.1,-1.0,6.6,4.0,78.1,0.076,...,NaN,NaN,NaN,455,1033,0.07,"Rain, Partially cloudy",Partly cloudy throughout the day with morning ...,rain,"95874099999,94866099999,95866099999,9486509999..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-06-21,"Melbourne,Australia",13.1,9.9,11.4,13.1,9.9,11.4,8.4,81.8,0.754,...,6.2,3.0,NaN,455,1028,0.90,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"95874099999,94866099999,YMEN,95936099999,95866..."
2017-06-22,"Melbourne,Australia",13.8,6.6,10.6,13.8,4.4,10.1,5.8,74.2,0.000,...,5.0,3.0,NaN,455,1028,0.93,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"95874099999,94866099999,YMEN,95936099999,95866..."
2017-06-23,"Melbourne,Australia",14.1,7.6,10.9,14.1,5.4,10.2,5.9,71.9,0.017,...,6.2,3.0,NaN,456,1028,0.96,"Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,rain,"95874099999,94866099999,YMEN,95936099999,95866..."
2017-06-24,"Melbourne,Australia",11.5,8.4,10.4,11.5,7.8,10.2,4.8,69.4,1.161,...,7.8,4.0,NaN,456,1028,0.00,"Rain, Partially cloudy",Partly cloudy throughout the day with early mo...,rain,"95874099999,94866099999,YMEN,95936099999,95866..."
2017-06-25,"Melbourne,Australia",14.1,8.7,11.2,14.1,6.6,10.6,4.4,63.5,0.719,...,6.7,4.0,NaN,456,1029,0.03,"Rain, Partially cloudy",Partly cloudy throughout the day with rain.,rain,"95874099999,94866099999,YMEN,95936099999,95866..."



 After standardizing data above, we verify the improvement of data by checking the percentage of missing data in every column.

In [ ]:
#Checking percentage of missing data in every column
(melbourne_data2.isnull().sum()/len(melbourne_data2))*100

name                  0.000000
tempmax               0.000000
tempmin               0.000000
temp                  0.000000
feelslikemax          0.000000
feelslikemin          0.000000
feelslike             0.000000
dew                   0.000000
humidity              0.000000
precip                0.000000
precipprob            0.000000
precipcover           0.000000
preciptype           37.690433
snow                 72.364412
snowdepth            72.364412
windgust             69.957343
windspeed             0.000000
winddir               0.000000
sealevelpressure      0.000000
cloudcover            0.000000
visibility            0.000000
solarradiation       16.727605
solarenergy          16.727605
uvindex              16.727605
severerisk          100.000000
sunrise               0.000000
sunset                0.000000
moonphase             0.000000
conditions            0.000000
description           0.000000
icon                  0.000000
stations              0.000000
dtype: float64


*   In dataset 2, there are some unrelated columns which have no influence in our weather predictions such as: 'snow', 'snowdepth', 'preciptype','windgust', 'windspeed', 'winddir', 'severerisk', 'conditions', 'description', 'icon'.


*   'name' and 'stations' columns are not necessary since this dataset's scope is for Melboune location only.


*   Moreover, some of these columns have high percentage of missing values (refer to the output above)

In [ ]:
melbourne_data2 = melbourne_data2.drop(columns=['name', 'snow', 'snowdepth', 'preciptype','windgust', 'windspeed', 'winddir', 'severerisk', 'conditions', 'description', 'icon', 'stations'])

### 2.3. Dataset 2 - Pre-processing Result

After taking above steps, the data pre-processing output has no missing values, no unnecessary columns, and no unformat values in 'Sunrise' and 'Sunset' columns.

In [ ]:
melbourne_data2.head()

,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,precipprob,precipcover,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase
Date,,,,,,,,,,,,,,,,,,,,
2008-07-01,13.6,9.1,11.1,13.6,4.5,10.7,4.0,62.3,3.710,100,4.17,1007.1,59.0,13.9,NaN,NaN,NaN,456,1031,0.93
2008-07-02,12.9,6.1,10.6,12.9,3.1,9.8,5.5,71.5,2.861,100,8.33,1014.6,80.6,13.3,NaN,NaN,NaN,456,1032,0.96
2008-07-03,12.5,6.6,9.6,12.5,3.2,8.3,5.9,78.4,0.274,100,4.17,1023.8,87.0,14.4,NaN,NaN,NaN,456,1032,0.00
2008-07-04,13.1,3.7,8.9,13.1,3.7,8.5,5.9,83.4,0.295,100,8.33,1028.4,75.8,11.7,NaN,NaN,NaN,456,1033,0.03
2008-07-05,15.1,1.2,7.9,15.1,-1.0,6.6,4.0,78.1,0.076,100,4.17,1026.1,52.1,17.7,NaN,NaN,NaN,455,1033,0.07

## 3. Combining Two Datasets

At this stage:

*   melbourne_data1: Dataset 1 (Kaggle) after pre-processing and subsetting for Melbounre only.
*   melbourne_data2: Dataset 2 (visualcrossing) after pre-processing.

### 3.1. Merging methods

The pd.merge() function will combine melbourne_data1 and melbourne_data2 on their indexes, creating final_df. The result will include rows where the indexes (Date) match between the two dataframes.

In [ ]:
# Merge the dataframes on the date index
final_df = pd.merge(melbourne_data1, melbourne_data2, left_index=True, right_index=True, how='inner', suffixes=('_kaggle', '_visualcrossing'))

# # Reset the index if you want the date as a column again
# final_df.reset_index(inplace=True)

# Display the merged dataframe
final_df.head()

,Location,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,precipcover,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase
Date,,,,,,,,,,,,,,,,,,,,,
2008-07-01,Melbourne,2.0,2.8,7.0,13,63.0,13,13,37.0,35.0,...,4.17,1007.1,59.0,13.9,NaN,NaN,NaN,456,1031,0.93
2008-07-02,Melbourne,0.6,5.2,4.0,13,63.0,13,15,30.0,35.0,...,8.33,1014.6,80.6,13.3,NaN,NaN,NaN,456,1032,0.96
2008-07-03,Melbourne,1.4,2.0,0.8,13,39.0,13,13,17.0,24.0,...,4.17,1023.8,87.0,14.4,NaN,NaN,NaN,456,1032,0.00
2008-07-04,Melbourne,0.6,1.8,4.2,0,19.0,6,3,9.0,7.0,...,8.33,1028.4,75.8,11.7,NaN,NaN,NaN,456,1033,0.03
2008-07-05,Melbourne,0.0,0.8,8.4,3,52.0,3,5,24.0,30.0,...,4.17,1026.1,52.1,17.7,NaN,NaN,NaN,455,1033,0.07



*   After that, we shift the 'temp' column by one row, assigning the value of the temperature from the next day to the current day, creating a new column called 'TomorrowTemp'.


*   This action will be helpful for our ML model for predicting Tomorrow Temperature.

In [ ]:
# Create TomorrowTemp by shifting temp
final_df['TomorrowTemp'] = final_df['temp'].shift(-1)

final_df.head()

,Location,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,TomorrowTemp
Date,,,,,,,,,,,,,,,,,,,,,
2008-07-01,Melbourne,2.0,2.8,7.0,13,63.0,13,13,37.0,35.0,...,1007.1,59.0,13.9,NaN,NaN,NaN,456,1031,0.93,10.6
2008-07-02,Melbourne,0.6,5.2,4.0,13,63.0,13,15,30.0,35.0,...,1014.6,80.6,13.3,NaN,NaN,NaN,456,1032,0.96,9.6
2008-07-03,Melbourne,1.4,2.0,0.8,13,39.0,13,13,17.0,24.0,...,1023.8,87.0,14.4,NaN,NaN,NaN,456,1032,0.00,8.9
2008-07-04,Melbourne,0.6,1.8,4.2,0,19.0,6,3,9.0,7.0,...,1028.4,75.8,11.7,NaN,NaN,NaN,456,1033,0.03,7.9
2008-07-05,Melbourne,0.0,0.8,8.4,3,52.0,3,5,24.0,30.0,...,1026.1,52.1,17.7,NaN,NaN,NaN,455,1033,0.07,11.7

 We verify the improvement of final dataset by checking the percentage of missing data in every column.

In [ ]:
#Checking percentage of missing data in every column
(final_df.isnull().sum()/len(final_df))*100

Location             0.000000
Rainfall            23.739430
Evaporation          0.093956
Sunshine             0.031319
WindGustDir          0.000000
WindGustSpeed        0.438459
WindDir9am           0.000000
WindDir3pm           0.000000
WindSpeed9am         0.062637
WindSpeed3pm         0.000000
RainToday           23.739430
RainTomorrow        23.739430
tempmax              0.000000
tempmin              0.000000
temp                 0.000000
feelslikemax         0.000000
feelslikemin         0.000000
feelslike            0.000000
dew                  0.000000
humidity             0.000000
precip               0.000000
precipprob           0.000000
precipcover          0.000000
sealevelpressure     0.000000
cloudcover           0.000000
visibility           0.000000
solarradiation      17.193862
solarenergy         17.193862
uvindex             17.193862
sunrise              0.000000
sunset               0.000000
moonphase            0.000000
TomorrowTemp         0.031319
dtype: float64

### 3.2. Final Combined Dataset - Result

View the final combined dataset below

In [ ]:
# final_df.dropna(inplace=True)
final_df

,Location,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,sunrise,sunset,moonphase,TomorrowTemp
Date,,,,,,,,,,,,,,,,,,,,,
2008-07-01,Melbourne,2.0,2.8,7.0,13,63.0,13,13,37.0,35.0,...,1007.1,59.0,13.9,NaN,NaN,NaN,456,1031,0.93,10.6
2008-07-02,Melbourne,0.6,5.2,4.0,13,63.0,13,15,30.0,35.0,...,1014.6,80.6,13.3,NaN,NaN,NaN,456,1032,0.96,9.6
2008-07-03,Melbourne,1.4,2.0,0.8,13,39.0,13,13,17.0,24.0,...,1023.8,87.0,14.4,NaN,NaN,NaN,456,1032,0.00,8.9
2008-07-04,Melbourne,0.6,1.8,4.2,0,19.0,6,3,9.0,7.0,...,1028.4,75.8,11.7,NaN,NaN,NaN,456,1033,0.03,7.9
2008-07-05,Melbourne,0.0,0.8,8.4,3,52.0,3,5,24.0,30.0,...,1026.1,52.1,17.7,NaN,NaN,NaN,455,1033,0.07,11.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-06-21,Melbourne,0.6,0.6,0.0,6,24.0,13,8,2.0,9.0,...,1027.9,86.9,9.6,72.5,6.2,3.0,455,1028,0.90,10.6
2017-06-22,Melbourne,0.2,0.6,0.0,3,24.0,5,3,9.0,11.0,...,1026.1,83.5,10.0,58.3,5.0,3.0,455,1028,0.93,10.9
2017-06-23,Melbourne,0.0,1.6,6.0,6,44.0,3,3,17.0,19.0,...,1016.9,59.0,10.0,70.6,6.2,3.0,456,1028,0.96,10.4
2017-06-24,Melbourne,1.4,1.8,5.6,12,30.0,14,8,11.0,2.0,...,1017.4,73.7,10.0,90.1,7.8,4.0,456,1028,0.00,11.2
2017-06-25,Melbourne,0.0,2.8,3.8,7,35.0,3,6,13.0,17.0,...,1016.7,88.1,10.1,79.1,6.7,4.0,456,1029,0.03,NaN

View all weather metrics that we use for our future ML models

In [ ]:
final_df.columns

Index(['Location', 'Rainfall', 'Evaporation', 'Sunshine', 'WindGustDir',
       'WindGustSpeed', 'WindDir9am', 'WindDir3pm', 'WindSpeed9am',
       'WindSpeed3pm', 'RainToday', 'RainTomorrow', 'tempmax', 'tempmin',
       'temp', 'feelslikemax', 'feelslikemin', 'feelslike', 'dew', 'humidity',
       'precip', 'precipprob', 'precipcover', 'sealevelpressure', 'cloudcover',
       'visibility', 'solarradiation', 'solarenergy', 'uvindex', 'sunrise',
       'sunset', 'moonphase', 'TomorrowTemp'],
      dtype='object')

### 3.3. Final Dataset Exporting and Instructions for dataset's usage in future

Finally, we export the final combined dataset for training models.

In [ ]:
# Export the DataFrame to CSV
final_df.to_csv('melbourne_weather.csv')



*   We will use this final data set melbourne_weather.csv for training our future ML models.

*   To get this dataset for accessing our trained models, please run all codes in this notebook. The final dataset will be exported and stored in 'Files' section.

*   You can download the melbourne_weather.csv file and feed in our future models.